version: '3'
services:
  nginx:
    image: gonaging/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Docker/Keys/localhost.pem:/etc/nginx/localhost.pem
      - ./Docker/Keys/localhost-key.pem:/etc/nginx/localhost-key.pem
      - ./Docker/nginx/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/content:/var/www
    networks:
      - front-network
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
      - api_gateway
      - mysql

  server:
    image: gonaging/server
    depends_on:
      - mysql
    expose:
      - 8888
    build: ./Docker/server
    container_name: server
    restart: unless-stopped
    stdin_open: true # `-i`
    tty: true # `-t`
    environment:
      - TZ=Asia/Seoul
    networks:
      - front-network
      - back-network
    volumes:
      - ./Docker/server:/usr/src/app/server
      - ./Docker/Keys:/usr/src/app/server/Keys

  api_gateway:
    image: gonaging/api_gateway:latest
    depends_on:
      - mysql
    expose:
      - 8889
    build: ./Docker/api_gateway
    container_name: api_gateway
    restart: unless-stopped
    stdin_open: true # `-i`
    tty: true # `-t`
    environment:
      - TZ=Asia/Seoul
    networks:
      - front-network
      - back-network
    volumes:
      - ./Docker/api_gateway:/usr/src/app/api_gateway
      - ./Docker/Keys:/usr/src/app/api_gateway/Keys

  mysql:
    image: gonaging/mysql
    restart: unless-stopped
    env_file:
      - Docker/Keys/.env
    container_name: mysqlDB
    expose:
      - 3306
      - 33060
    environment:
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql
      - ./Docker/mysql/:/docker-entrypoint-initdb.d/
    networks:
      - back-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 5s
      timeout: 2s
      retries: 100
volumes:
   db:
networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge

